# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44359a163d7c01814679c0ffd9453128"
name = "rbx-bundle-test"
handle = "rbx-bundle-test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "rbx-outsmartly-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
